#!/bin/bash

# find the following parameters via the eclipse download page:
# http://download.eclipse.org/eclipse/downloads/
version="4.6-201606061100"
basename="org.eclipse.jdt.core.compiler.ecj-${version}"
baseurl="http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/eclipse/downloads/drops4/R-${version}/"

sources() {
	src=${basename}-sources.jar
	curl "${baseurl}ecjsrc-4.6.jar" > ${src}
	unzip -t ${src} &> /dev/null
}

binary() {
	bin=${basename}.jar
	curl "${baseurl}ecj-4.6.jar" > ${bin}
	unzip -t ${bin} &> /dev/null
}

javadoc() {
	echo 'For javadoc, please see the source jar' > README
	jar cf ${basename}-javadoc.jar README
	rm README
}

pom() {
	sed -i "s#\(<version>\)\(</version>\)#\1${version}\2#" pom.xml
	sed -i "s#\(<version>\)\(</version>\)#\1${version}\2#" ../pom.xml
}

sign() {
	gpg --armor --detach-sign pom.xml
	mv pom.xml.asc ${basename}.pom.asc
	gpg --armor --detach-sign ${bin}
	gpg --armor --detach-sign ${src}
	gpg --armor --detach-sign ${basename}-javadoc.jar 
}

install() {
	mvn install:install-file -Dfile=${bin} -DpomFile=pom.xml
}

set -e
sources
binary
javadoc
pom
sign
install
