#!/bin/bash

# find the following parameters via the eclipse download page:
# http://download.eclipse.org/eclipse/downloads/
version="4.7"
release="201706120950"
releasetype="R" #R - release, S - Stable, I - Integration

versionfull="${version}-${release}"
basename="org.eclipse.jdt.core.compiler.ecj-${versionfull}"
baseurl="http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/eclipse/downloads/drops4/${releasetype}-${versionfull}/"

sources() {
	src=${basename}-sources.jar
	curl "${baseurl}ecjsrc-${version}.jar" > ${src}
	unzip -t ${src} &> /dev/null
}

binary() {
	bin=${basename}.jar
	curl "${baseurl}ecj-${version}.jar" > ${bin}
	unzip -t ${bin} &> /dev/null
}

javadoc() {
	echo 'For javadoc, please see the source jar' > README
	jar cf ${basename}-javadoc.jar README
	rm README
}

replace-jdt-version() {
	replace-version "$1" 'org.eclipse.jdt.core.compiler.ecj' "${versionfull}"
}

replace-lec-version() {
	replace-version "$1" 'lombok-eclipse-compiler' "${version}-SNAPSHOT"
}

replace-version() {
	sed -i "/<artifactId>$2<\/artifactId>/{n; s/<version>[^<]*<\/version>/<version>$3<\/version>/}" "$1"
}

pom() {
	
	replace-jdt-version ../../pom.xml
	cp ../../pom.xml ./${basename}.pom.xml
	replace-jdt-version ../../../pom.xml
	replace-lec-version ../../../pom.xml
}

sign() {
	echo
	echo '### You are about to be asked for your PGP passphrase 4 times ###'
	gpg --armor --detach-sign ${basename}.pom.xml
	mv ${basename}.pom.{xml.,}asc
	gpg --armor --detach-sign ${bin}
	gpg --armor --detach-sign ${src}
	gpg --armor --detach-sign ${basename}-javadoc.jar
}

install() {
	mvn install:install-file -Dfile=${bin} -DpomFile=${basename}.pom.xml
}

cd-target() {
	cd "$( dirname "${BASH_SOURCE[0]}" )"
	rm -Rf target
	mkdir -p target/"${versionfull}"
	cd target/"${versionfull}"
}

set -e
cd-target
sources
binary
javadoc
pom
sign
install
